export const ADD_DATA = 'ADD_DATA';
export const DELETE_NOTE = 'DELETE_NOTE';
export const CHANGE_EDIT_STATUS = 'CHANGE_EDIT_STATUS';
export const CHANGE_ADD_STATUS = 'CHANGE_ADD_STATUS';
export const GET_DATA_EDIT = 'GET_DATA_EDIT';
export const UPDATE_LIST = 'UPDATE_LIST';